### ISSUE TITLE
send email to external users PnP core js

### ISSUE THREAD

**Issue by NasirSP** [SharePoint/PnP-JS-Core#709] opened 2018-01-30 11:46 UTC
I'm trying to send email to external users, I've a contact us form having an email address textbox so when a user submit contact us form i need to send email to the email address mentioned in the textbox and it could be any email e.g exchange/outlook, gmail, yahoo etc here is my code

```
const emailProps: EmailProperties = {
      To: ["xyz@gmail.com"],
      Subject: "This email is about...",
      Body: "Here is the body. <b>It supports html</b>"
    };
    pnp.sp.utility.sendEmail(emailProps).then(_ => {
      console.log("Email Sent!");
    });
```

Error while sending email
**Uncaught (in promise) Error: Error making HttpClient request in queryable: [400] Bad Request**

**Comment by koltyakov** [comment] 2018-01-30 11:54
Hey @NasirSP, 

What is the message in response body?

Steps:

- Execute in Chrome
- Click on error message (opens network tab)
- Error request's response tab

**Comment by NasirSP** [comment] 2018-01-30 12:40
{"odata.error":{"code":"-2130575251, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The security validation for this page is invalid and might be corrupted. Please use your web browser's Back button to try your operation again."}}}

**Comment by patrick-rodgers** [comment] 2018-01-30 15:31
@NasirSP - this doesn't appear to be an issue with the library as sending email works in my testing. You may need to review the docs on sending email through SharePoint REST and the settings for the tenant. You can also post this question in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) as well.

A search would let you know that you can only send email to site users via REST. This is by design and is for security. Closing this as answered. Thanks!

**Closed by patrick-rodgers** 2018-01-30 15:31 UTC
Labels: Fixed / Answered, question

**Comment by NasirSP** [comment] 2018-01-31 06:18
Yesterday I had done some search on it and found that REST API or PnP Core JS only sends the email to SharePoint site users NOT to external users
http://ServerName:Port/_api/SP.Utilities.Utility.SendEmail

Thanks

**Comment by Shyammi** [comment] 2018-06-12 07:10
Hi,
I'm trying to send email to the current user on item creation. The send email utility is working well when the and cc are hardcoded, but not when trying to assign dynamic values.

$pnp.sp.utility.sendEmail({
	To: currentuseremail,                                        //defining this way doesn't work
	CC: ["shyam.sundar1@astrazeneca.com"],	//defining this way works
	Subject: "A new draft PVA created",
	Body: body,
})

Any help would be much appreciated.
