### ISSUE TITLE
Error "TS2300: Duplicate identifier 'Promise'" after installing in a SPFx project

### ISSUE THREAD

**Issue by PeppeDotNet** [SharePoint/PnP-JS-Core#267] opened 2016-11-21 10:03 UTC
#### Category
Question

#### Expected / Desired Behavior / Question
After installing pnp-js-core I cannot build my project. There is something that I've missed?

#### Observed Behavior
I install pnp-js-core using npm in a SPFx project. Once downloaded I tried to build the project using "gulp build" and I get a lot of errors like this one:
[03:49:51] Error - typescript - node_modules/@types/core-js/index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.

#### Steps to Reproduce
npm install pnp-js-core --save-dev
gulp build

**Comment by KEMiCZA** [comment] 2016-11-21 13:18
Hi PeppeDotNet

The following works for me: 
npm install **sp-pnp-js** --save

You used: **pnp-js-core**

Maybe there's a difference? When I used "pnp-js-core" NPM couldn't find the package.

**Comment by patrick-rodgers** [comment] 2016-11-21 14:09
This is actually a duplicate of #221. I've updated the title of that issue to try and make it easier to find. The workaround is described in that thread and we are working with the PG to ensure things are sorted by release. Thanks for reporting this.

**Closed by patrick-rodgers** 2016-11-21 14:09 UTC
