### ISSUE TITLE
Typescript compile error when trying to save multiselect choices object

### ISSUE THREAD

**Issue by dev4201** [SharePoint/PnP-JS-Core#265] opened 2016-11-17 18:51 UTC
#### Category
[x] Bug
I have a multiselect value that I'm trying to save back to SharePoint.

**Here is what works**
I was able to figure out a way to save multiselect choices by executing the following script on the site:

`$pnp.sp.web.lists.getByTitle('My List').items.add({
Title: 'Test Title',
MultiChoiceColumn:  {"results":["choice value 1", "choice value 2"]}
  })`

But, when I try doing the same in Typescript, I get compiler error, here is an example code:

` saveNew() {
        var multiselectChoices = { "results": ["choice value 1", "choice value 2"] };
       
        pnp.sp.web.lists.getByTitle('My List').items.add({
            Title: 'Test Tilte',          
            MyMultiSelectColumn: multiselectChoices
        }).then(result => {
            console.log('SAVED NEW ITEM ' + JSON.stringify(result));
        })
    }`
**Here is the error I get from ts **

> MyMultiSelectColumn is not assignable to parameter of type TypedHash<string | number | boolean> 

> Property 'MyMultiSelectColumn' is incompatible with index signature

I ended up executing the code with Typescript error and it worked but I wanted to mention this to community in case it should be considered as a bug or am I simply doing something wrong?

**BTW - sp-pnp-js is AWESOME, THANK YOU for making my SP API coding better and cleaner!**

**Comment by patrick-rodgers** [comment] 2016-11-18 15:19
Thanks for reporting this @dev4201, we'll try and have a look early next week. Thanks!

**Comment by patrick-rodgers** [comment] 2016-11-23 14:48
@dev4201 - so just having a chance to look at this. Seems like the issue is with the typing of the TypedHash parameter? There is no way we can add a typing to cover all the cases so might need to expand the typing there to "any". I'll have a look as there would then be at least a few other places where this change is required.

Glad you are enjoying the library :)

**Comment by rgarita** [comment] 2016-12-08 01:45
Hello, just to add some extra info.

I'm having the same issue with a multi-user field. This also is affecting the update() function. 

The workaround we found was temporary modify the typing for the operation allowing Objects. 

Raul

**Comment by patrick-rodgers** [comment] 2016-12-08 14:37
Thanks @rgarita - have this actually fixed but not able to merge to dev yet due to some other things I'm working on. Will discuss on today's call if you can make it.

**Comment by patrick-rodgers** [comment] 2016-12-30 18:44
This is fixed in dev branch, add/update now take TypedHash<any>.

**Closed by patrick-rodgers** 2016-12-30 18:44 UTC
Labels: bug

**Comment by coolsambit** [comment] 2017-04-27 21:30
I cloned the solution:
git clone https://github.com/SharePoint/PnP-JS-Core.git npmcore. It created a folder the below folder structure  "C:\Users\sswain1\Desktop\Angular\npmcore\PnP-JS-Core>"

I am trying to follow the instructions and file the command:

   npm install sp-pnp-js --save

I get the error: 

npm ERR! Refusing to install package with name "sp-pnp-js" under a package
npm ERR! also called "sp-pnp-js". Did you name your project the same

C:\Users\sswain1\Desktop\Angular\npmcore\PnP-JS-Core>bower install sp-pnp-js
'bower' is not recognized as an internal or external command,
operable program or batch file.

Thus I am not even able to transpile or do anything with it.
Can anyone guide what is that I am doing wrong here?

**Comment by koltyakov** [comment] 2017-04-27 22:00
Hi @coolsambit,

1\. You don't have to clone the project if you're going just using the library as a reference in your project.
2\. It's a standard NPM behavior to prevent installation of a module with the same name as a folder name. You just can't install, let's say, `lodash` in a project's folder with the name `lodash`.
3\. For using `bower` it should be installed globally with `npm install bower -g`, bower is a package manager usually used for frontend libraries. You can stick to npm and just do not use bower in your projects if there is any specific purpose for that.
4\. You posted this in TypeScript related issue thread, not sure, but if you going using pnp-js-core with typescript you should use npm installation.
