### ISSUE TITLE
getItemsByCAMLQuery in a site with variation enabled getting not found

### ISSUE THREAD

**Issue by mauricionr** [SharePoint/PnP-JS-Core#170] opened 2016-08-08 14:29 UTC
#### Category

[ ] Enhancement

[x ] Bug

[X] Question
#### Expected / Desired Behavior / Question

I have an site with variations enable, i'm using this method to get item from a library

``` javascript
pnp.sp.web.lists.getByTitle(Title).getItemsByCAMLQuery(Caml)
```

I'm getting 404 because the request url is not the correct url
#### Observed Behavior

this is the current url 

`{siteurl}/pt-br/Paginas/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`
`{siteurl}/{lang}/Paginas/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`

the url should be this one

`{siteurl}/pt-br/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`
`{siteurl}/{lang}/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`
#### Steps to Reproduce
1. Publishing site with variation enable
2. Try get items from library
#### Question

How to change the request url on `pnp.setup`, it is possible?

``` javascript

pnp.setup({
        headers: {
          "Accept": "application/json; odata=verbose"
       }
    }); 

```

Thanks!

**Comment by patrick-rodgers** [comment] 2016-08-12 20:27
Hi Maricio - sorry not 100% sure on the issue, though clearly there is one. Help me understand so we can get it fixed!

Are you in one site, (Site A) and trying to call a second site (Site B)? So what you are really lacking is a way to say that "I am in Site A and want to make a request to Site B which has a different url?" 

OR is this actually an issue with variations?

I'll try and setup a site with variations next week to test this out - thanks for reporting it!

**Comment by mauricionr** [comment] 2016-08-13 13:25
@patrick-rodgers the error happens when i'm trying to get items in the same site, the request is adding the `/Paginas` in the request url causing the error.

but i have some situations that i need to get itens from the parent site, this could be another issue.

got it?

Thanks!

**Comment by mauricionr** [comment] 2016-08-14 00:45
@patrick-rodgers i will check out if i can send a backup for you, it is a on primise sharepoint project, ok?

**Comment by mike-morrison** [comment] 2016-08-15 22:43
@mauricionr @patrick-rodgers I would expect the correct URL to look like:

{siteurl}/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=

Without the language.

Can you confirm if this URL works or does it require the language part?  Sorry I don't have an environment where I can install language packs without building a new environment.

**Comment by mauricionr** [comment] 2016-08-16 12:17
@mike-morrison the variation has created a sub site for each language, i can access via postman the _api stuff without `/Paginas/`, the problem is the `/Paginas/`path in the url.

- correct url(without `/Paginas/`
  `{siteurl}/{lang}/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`

- incorret(with `/Paginas/`)
  `{siteurl}/{lang}/Paginas/_api/web/lists/getByTitle('Banner%20Carrossel')/getitems?$expand=`

the context here is we have a ***publishing*** site with variation enable.

first i thought that the problem was with ***variation***, now i guess that the problem is the ***publishing site*** stuff

in the browser with ***publishing site*** enable i access pages with paths like this one:
#### https://{siteurl}/{lang}/Paginas/{pageName}.aspx

**Comment by bbouski** [comment] 2016-11-04 05:33
I have the same issue '404 not found' on a publishing site, retrieving user specific items from a list in the rootWeb. 

```
var viewXml = ['<View>',
                        '<RowLimit>10</RowLimit>',
                            '<Query>',
                                '<Where>',
                                    '<Or>',
                                        '<Eq>',
                                            '<FieldRef Name="Users" />',
                                            '<Value Type="Integer">',
                                            '<UserID />',
                                            '</Value>',
                                        '</Eq>',
                                        '<Membership Type="CurrentUserGroups">',
                                            '<FieldRef Name="Users" />',
                                        '</Membership>',
                                    '</Or>',
                                '</Where>',
                                '</Query>',
                                '<ViewFields>',
                                    '<FieldRef Name="Title" />',
                                '</ViewFields>',
                            '</View>'].join('');

$pnp.sp.site.rootWeb.lists.getByTitle('User Items').getItemsByCAMLQuery({ ViewXml: viewXml });
```

**Comment by patrick-rodgers** [comment] 2016-11-04 14:59
Hi @mauricionr & @bbouski,

Just had a look on this today and could not duplicate. I think the issue is that you are making the request before the _spPageContextInfo is available to the library. Before making the request you can either use something like jquery's $(function() { // ... }); syntax or create a loop to check for existing of that var and wait. I don't want to add something like this to the library as it would block some use cases and there are established ways to determine if the page is loaded. Please give that a try and let me know if we can indeed close this issue.

Thanks!

**Comment by bbouski** [comment] 2016-11-07 20:44
Thanks after waiting for page context to be available it runs fine. 
 ExecuteOrDelayUntilScriptLoaded(function(){
                        $pnp.sp.site.rootWeb.lists.getByTitle('User Items').getItemsByCAMLQuery({ ViewXml: viewXml }).then(resolve);
                    }, "core.js");

**Comment by patrick-rodgers** [comment] 2016-11-08 16:15
Ok, going to close - please do reopen is this issue is not actually related to the page load time

**Closed by patrick-rodgers** 2016-11-08 16:15 UTC
Labels: question
