### ISSUE TITLE
Issue when Update the listItemAllFields item from a file

### ISSUE THREAD

**Issue by ravenboilinux** [SharePoint/PnP-JS-Core#305] opened 2017-01-20 14:49 UTC
#### Category
[] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
When you upload a file, you can use the listItemAllFields property to update the metadata with that file. This can done with the other frameworks for interacting with sharepoint api.

#### Observed Behavior
When you update the listItemAllFields, you get this error:
An entry without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.

###Some more notes
The mean reason for this error is that type in the __metadata field is blank. It be pulling it from the ListItemEntityTypeFullName property on parentlist (after it fetch the metadata from parent list). The PNP framework uses this url for the parent list "_api/web/getFolderByServerRelativeUrl('Document Attactments')" which  return an SP.Folder object not SP.List object. I hope this can help. :) 

#### Steps to Reproduce
1. Create a Document Libarary called "Document Attactments"
2. Upload a file using the framework
3. Update the listItemAllItems item

**Comment by patrick-rodgers** [comment] 2017-01-20 14:53
Can you share your code? The getFolderByServerRelativeUrl returns a folder by design.

**Comment by ravenboilinux** [comment] 2017-01-20 14:54
pnp.sp.web.getFolderByServerRelativeUrl("Document Attactments").files.add(fileName, file, true).then((results) => {
            
            results.file.listItemAllFields.update({
                    Document_x0020_TypeId: 1,
                    RequestId: this.requestID.ToSerialized(),
                    Title:file.name
                }).then((results)=>{
                    this.ShowMainForm()
                }).catch((reason) => {
                    alert("[ListItemUpdate] " + reason);
                })
        }).catch((reason) => {
            alert("[FileUpload] " + reason);
        })

**Comment by ravenboilinux** [comment] 2017-01-20 16:15
When I look at the network traffic, it posts to the url 
_api/web/getFolderByServerRelativeUrl('Document Attactments')/files('asdfasdf_Plant Questionnaire (optional).csv')/listItemAllFields 
with the following json object:
```javascript
{
       "__metadata":{},
       "Document_x0020_TypeId":1,
       "RequestId":"e19640d1-6374-4df6-8dcb-3849ca4e6144",
       "Title":"BudgetItem.csv"
}

**Comment by patrick-rodgers** [comment] 2017-01-26 14:27
Hi @ravenboilinux - after reviewing this it appears that this is a mistake in our implementation of the API. That property should not return an Item instance as it is readonly, as [shown here](https://msdn.microsoft.com/en-us/library/office/dn450841.aspx#bk_FileProperties). In other words this isn't a valid endpoint to operate on an item. So you won't be able to update the file's item in the manner you outlined above, though I get why you thought you could - since the library lets you.  I've fixed this in #309.

**Comment by patrick-rodgers** [comment] 2017-01-26 14:28
Closed as fixed in #309.

**Closed by patrick-rodgers** 2017-01-26 14:28 UTC
Labels: bug

**Comment by ravenboilinux** [comment] 2017-01-26 14:30
Thank you very much.

**Comment by JackHu88** [comment] 2017-03-07 03:06
Hi @ravenboilinux , 
How it fix your issue? when it use this way to update the metadata, it show me the error below:
results.file.listItemAllFields.update is not a function, how you update update the metadata with that file ?
Thanks

**Comment by ravenboilinux** [comment] 2017-03-09 16:40
They removed the function to fix this. You have to take the ID from listItemAllFields and get the listitem from the list version of document lib. That way the url is formed correctly.


```javascript
pnp.sp.web.getFolderByServerRelativeUrl(folderName).files.add(fileName, file, true).then((results) => {
      results.file.listItemAllFields.get().then((FileAllFields) => {
         pnp.sp.web.lists.getByTitle(folderName).items.getById(FileAllFields.Id).update({
                      update object.
                })
      ))
})

**Comment by JackHu88** [comment] 2017-03-10 01:46
Thanks ravenboilinux,

One more question, if i want add multiple level folders, i need to add one under one like below?
$pnp.sp.web.getFolderByServerRelativeUrl(folderName).folders.add(folder1).then(function(result){
	result.folder.folders.add(folder2).then(function(d){
              d.folder.folders.add(folder3).then(function(d){})
       })
})
Do you know a best way can add these folders one time?

**Comment by ravenboilinux** [comment] 2017-03-10 03:14
you want to make a batch for all your requests. Batching will allow you to group your request to one server request. 
https://github.com/SharePoint/PnP-JS-Core/wiki/Batching

**Comment by JackHu88** [comment] 2017-03-10 03:20
@ravenboilinux Does it can work for multiple level folders?

**Comment by ravenboilinux** [comment] 2017-03-10 03:55
as long as you do in order like this

```javascript
let batch = pnp.sp.createBatch();
$pnp.sp.web.getFolderByServerRelativeUrl(folderName).folders.inbatch(batch).add(folder1RelatedServerUrl).then(r => {
    console.log(r)
});
$pnp.sp.web.getFolderByServerRelativeUrl(folderName).folders.inbatch(batch).add(folder2RelatedServerUrl).then(r => {
    console.log(r)
});
$pnp.sp.web.getFolderByServerRelativeUrl(folderName).folders.inbatch(batch).add(folder3RelatedServerUrl).then(r => {
    console.log(r)
});
batch.execute().then(() => console.log("All done!"));

**Comment by JackHu88** [comment] 2017-03-10 04:58
Thanks @ravenboilinux

**Comment by ravenboilinux** [comment] 2017-03-10 13:43
One thing to keep in mind that REST API Batching is only suppoerted for SharePoint Online and SharePoint 2016 not 2013 or 2010
