### ISSUE TITLE
Search POSTQuery throws an error on multiple consecutive calls

### ISSUE THREAD

**Issue by Sartor87** [SharePoint/PnP-JS-Core#480] opened 2017-05-31 07:37 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.5]

#### Expected / Desired Behavior / Question
Expected query should return results

#### Observed Behavior
On the secondary request, the library throws an exception saying "An unexpected 'StartObject' node was found when reading from the JSON reader. A 'StartArray' node was expected".

#### Steps to Reproduce
Sample base query object:
`searchObject: {
            Querytext: "Path:\"" + _spPageContextInfo.siteAbsoluteUrl + "\" AND (ContentType:\"My Content Type 1\" OR ContentType:\"My Content Type 2\")",
            RowLimit: 16,
            SelectProperties: ["Title", "Description", "ContentType", "PublishingImage", "ListItemID", "ListID"],
            SortList:
            [
                {
                    Property: 'Created',
                    Direction: $pnp.SortDirection.Descending
                }
            ]
        }`

Results are returned properly. Add another filter in the Querytext property, i.e.:

`searchObject: {
            Querytext: "Path:\"" + _spPageContextInfo.siteAbsoluteUrl + "\" AND (ContentType:\"My Content Type 1\" OR ContentType:\"My Content Type 2\") AND (owstaxIdMyManagedMetadataProp1:\"Value 1234\")",
            RowLimit: 16,
            SelectProperties: ["Title", "Description", "ContentType", "PublishingImage", "ListItemID", "ListID"],
            SortList:
            [
                {
                    Property: 'Created',
                    Direction: $pnp.SortDirection.Descending
                }
            ]
        }`

Results are filtered properly. Finally remove the newly added filter and process the with original query object - the error is thrown.

Thanks!

**Comment by patrick-rodgers** [comment] 2017-05-31 15:08
Hi @Sartor87 - two questions:

1) Is this something you are seeing with the getPage method?
2) can you share your actual code so we can clearly reproduce the issue?

Thanks!

**Comment by Sartor87** [comment] 2017-06-01 05:41
@patrick-rodgers 

1. No, this is initializing a completely new query

2. Here is a more complete sample:

`
MyNamespace = {
// omitted for brevity
getSearchData: function () {
// Logic for updating query text omitted - provided in the initial post
var searchObject = {
            Querytext: "",
            RowLimit: 16,
            SelectProperties: ["Title", "Description", "ContentType", "PublishingImage", "owstaxIdMyManagedMetadataProp1", "ListItemID", "ListID"],
            SortList:
            [
                {
                    Property: 'Created',
                    Direction: $pnp.SortDirection.Descending
                }
            ]
}

$pnp.sp.search(searchObject).then(function (response) { console.log(response); }).catch(function (r) {
                console.error(r);
            });
}
},

initEventHandlers: function () {
// event handler for clicking a DOM element which calls getSearchData
}
`

I'd like to point that out, when processing the query through an ordinary REST, it is processed properly.

**Comment by patrick-rodgers** [comment] 2017-06-02 21:02
Would it be possible to share the code that builds the query? If the query works two out of the three times I am wondering if however you are modifying it (removing a querytext filter as you state above) if the object is somehow becoming malformed.

You can also try the latest beta:

```
npm install sp-pnp-js@beta --save
```

If this is a case where you are holding a ref and we modify it adding the results: wrapper on say SortList twice. If that is the case I believe that to be fixed in the beta. If not I'd like to try and figure this out before the release next week. Thanks!

**Comment by Sartor87** [comment] 2017-06-05 06:25
@patrick-rodgers sure, here is a sample of the code (it always resets to a const query text string). I am providing the pure JS, we are currently not in the context of SPFx as we develop this component:

`
var originalQueryText = "Path:\"" + _spPageContextInfo.siteAbsoluteUrl + "\" AND (ContentType:\"My Content Type 1\" OR ContentType:\"My Content Type 2\"")"; // our const

searchObject.Querytext = originalQueryText;

if ($("#search-text-box .search-head").length > 0) { // my selector
searchObject.Querytext += " AND (";

$.each($("#search-text-box .search-head"), function (i, el) {
var termset = $(el).data("term-set"), searchCategory = $(el).data("term-cat");

if (i > 0) {
searchObject.Querytext += " OR ";
                    }

searchObject.Querytext += searchCategory + ":\"" + $(el).text().trim() + "\"";

});

searchObject.Querytext += ")";
}`

The current business logic works fine with regular REST call to postquery end point.

**Comment by patrick-rodgers** [comment] 2017-07-04 03:13
I haven't been able to reproduce this error given the information here. I think the issue is with how you are recreating the query for the third request. Since it works, then works, then fails it seems like something is getting held you aren't expecting?

**Comment by patrick-rodgers** [comment] 2017-07-11 19:38
Going to close this as I can't reproduce the problem with the library. If you do find a clear way to reproduce the issue please _reopen_ and let us know. Thanks!

**Closed by patrick-rodgers** 2017-07-11 19:38 UTC
Labels: investigate, Need More Information
