### ISSUE TITLE
Can not use latest version (1.0.5) with angular 2 setup

### ISSUE THREAD

**Issue by okaufmann** [SharePoint/PnP-JS-Core#248] opened 2016-11-01 15:19 UTC
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Expected / Desired Behavior / Question
If I use pnp-js-core in my angular 2 app (where core-js is a dependency) i can't compile the latest version 1.0.5 anymore. 1.0.4 works if I add typings for `microsoft.ajax` and `whatwg-fetch` additionally.

There are several hints that @typings/core-js causes the problem and should be removed:
https://github.com/angular/angular-cli/issues/1908
https://github.com/angular/angular-cli/issues/2106

#### Observed Behavior
```
ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:21:13
Duplicate identifier 'PropertyKey'.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:85:4
All declarations of 'name' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:145:4
Subsequent variable declarations must have the same type.  Variable '[Symbol.unscopables]' must be of type '{ copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but here has type 'any'.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:262:4
All declarations of 'flags' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:276:4
All declarations of 'EPSILON' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:311:4
All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:318:4
All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:457:4
Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:457:4
All declarations of '[Symbol.toStringTag]' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:464:4
All declarations of 'prototype' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:492:4
All declarations of 'hasInstance' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:498:4
All declarations of 'isConcatSpreadable' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:504:4
All declarations of 'iterator' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:510:4
All declarations of 'match' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:516:4
All declarations of 'replace' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:522:4
All declarations of 'search' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:528:4
All declarations of 'species' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:534:4
All declarations of 'split' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:540:4
All declarations of 'toPrimitive' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:546:4
All declarations of 'toStringTag' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:552:4
All declarations of 'unscopables' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:609:4
Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Math"', but here has type 'string'.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:609:4
All declarations of '[Symbol.toStringTag]' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:613:4
Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"JSON"', but here has type 'string'.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:613:4
All declarations of '[Symbol.toStringTag]' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:628:4
All declarations of 'size' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:634:4
All declarations of 'prototype' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:645:4
All declarations of 'size' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:651:4
All declarations of 'prototype' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:666:4
All declarations of 'prototype' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:680:4
All declarations of 'prototype' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:692:4
All declarations of 'value' must have identical modifiers.

ERROR in [default] C:\projects\test\node_modules\@types\core-js\index.d.ts:804:4
All declarations of 'prototype' must have identical modifiers.
```

#### Steps to Reproduce
- Create a plain project following this guide: https://angular.io/docs/ts/latest/guide/webpack.html
- Install pnp-js-core 1.0.5
- Compile

**Comment by patrick-rodgers** [comment] 2016-11-02 13:30
The issue is that if you include 1.0.5 in a non-angular project and remove @types/corejs you get errors on build. So I am not convinced that the 100% correct answer is to remove it as a dependency. I'll take a look at this a little deeper but seems to be caused by decisions made in the angular project.

**Comment by patrick-rodgers** [comment] 2016-11-02 19:40
Turns out I can't duplicate this. I followed the steps in the article you linked and create a project with all the files, npm install, ran it and everything worked (I could look at the web page with the logo). Then I 

`npm install sp-pnp-js --save`

Updated the app.component.ts and app.component.html to put a random string on the page using the pnp.util.getRandomString method. webpack bundle auto updated with file save and the page refreshed showing my string. Was also able to build using `npm run build` as described in the article.

I am using npm version 3.10.8 if that has any effect.

**Comment by patrick-rodgers** [comment] 2016-11-07 16:53
@okaufmann - were you able to retest this or provide any additional details? If not I'll be closing this as unable to reproduce. Thanks!

**Comment by patrick-rodgers** [comment] 2016-11-08 17:30
Going to close this as unable to reproduce, please do reopen if you can provide additional details. Thanks!

**Comment by Abrissirba** [comment] 2016-11-11 13:25
I'm getting this error too after upgrading to 1.0.6. Will investigate more and come back

**Comment by patrick-rodgers** [comment] 2016-11-12 16:08
I'll go ahead and reopen this, but if someone could please give me the additional steps to duplicate it? I followed what was in the article linked above and did not have issues. Are you installing other libraries? What specific actions are you taking with the library? What changes have you made to the default angular project as outlined in the article?

**Comment by patrick-rodgers** [comment] 2016-11-16 19:57
Just an update, still researching. I've removed core-js locally for myself and added es6-promise but an stuck on fetch typings file referencing es6 types when it isn't needed, as discussed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11290). So hoping that gets resolved and unblocks us. I don't really want to add a shim file to cover those types but might have to as a stop gap.

That being said, I still haven't been able to duplicate the above issue so somewhat guessing this will help.

**Comment by oka-garaio** [comment] 2016-11-22 17:45
I just found out that there was the following config section present in our tsconfig.js but not in the angular-webpack-tutorial ones:

```
"lib": [
      "dom",
      "es6"
    ]

```

When this was removed, it works. (This was introduced by typescript 2.0)

Can you proof this @Abrissirba ?

**Comment by Abrissirba** [comment] 2016-11-23 13:46
Same for me, when I removed the "lib" property from tsconfig the errors disappears :) Do you have any more information/links about why is this is happening in typescript 2.0 @oka-garaio?

**Comment by oka-garaio** [comment] 2016-11-30 14:39
The `lib` option is a new feature in ts 2.0. It controlls, which libraries should be included into the compilation. As far as I can see, does angular 2.0 with his own way by including es6 directly via typings (https://github.com/oka-garaio/angular-with-webpack/blob/master/src/polyfills.ts#L1).

This then cause the dublicate type definitions. 

Discussion in the Typescript repo: https://github.com/Microsoft/TypeScript/issues/6974

As this is no pnp-js-core bug, I close this issue now.

**Closed** 2016-12-01 16:45 UTC
Labels: investigate
