### ISSUE TITLE
Problem with urls when getting the item associated with a file

### ISSUE THREAD

**Issue by somartin90** [SharePoint/PnP-JS-Core#517] opened 2017-07-04 15:26 UTC
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

 [ 2.0.5 ]

#### Expected / Desired Behavior / Question

When I get the item associated with a file, the _parentUrl and _url properties of the QueryableShareableItem object, are relative to the current site and when I try to perform an update on the item, it returns me the error message that it can not find the list because it is trying to find the List in the current site instead of searching it at the specified site in the variable "relativeFileUrl".

This is a code example I am using:

`web.getFileByServerRelativeUrl(relativeFileUrl).select('Title').getItem().then((item) => {
                            console.log(item);
                            item.update({
                                Title: "Page Title"
                            }).then((r: ItemUpdateResult) => {
                            });
});`

The QueryableShareableItem object, has the following properties:

![image](https://user-images.githubusercontent.com/21335587/27835409-39a24a82-60db-11e7-9b88-8855bd085a88.png)

I have modified the _parentUrl and _url properties in the browser console, and the item update was successful.

Is it a bug or could it be that the request is wrong?

Thanks!

**Comment by patrick-rodgers** [comment] 2017-07-05 17:22
So you are getting a file using a web object which points to a different web? If you look at the source we use the returned item's metadata to create the item, but that is relative to the web it seems. I am not sure this is a bug - but is perhaps a place where we can improve the API. I will have to play with it, but I assume it will take an extra request but maybe not.

**Comment by patrick-rodgers** [comment] 2017-07-05 17:38
Well - testing this the issue is not that you are trying to get files from a different web - that produces an error "The object specified does not belong to a list.". Meaning this is indeed a bug when getting files from a sub web.

**Comment by patrick-rodgers** [comment] 2017-07-05 19:41
And fixed in PR #520. Thanks for reporting this. I'll be publishing a beta later today if you want to test out the change. Please _reopen_ this issue if you continue to see problems. Thanks!

**Closed by patrick-rodgers** 2017-07-05 19:41 UTC
Labels: bug, in progress!
