### ISSUE TITLE
Usage in TypeScript without importing

### ISSUE THREAD

**Issue by koltyakov** [SharePoint/PnP-JS-Core#342] opened 2017-03-03 11:57 UTC
Hi there,

#### Category
[ ] Enhancement
[ ] Bug
[x] Question

### Question

Could you please suggest me with a solution, how to reference `sp-pnp-js` in typescript project without actual importing the library?

I have `sp-pnp-js` applied globally in a bundle script within custom action ScriptLink or masterpage, no matter, so it's already on the pages. 
There are multiple solutions which use the library, some of them are written in TypeScript and packed with Webpack.

For convenient coding, `sp-pnp-js` is imported like this:

```javascript
import { Web } from 'sp-pnp-js';
```

But, as a result, `sp-pnp-js` "binaries" are placed to output .js and .map files.

Adding references like:

```javascript
/// <reference path="./../node_modules/sp-pnp-js/dist/pnp.d.ts" />
// or
/// <reference path="./../node_modules/sp-pnp-js/lib/pnp.d.ts" />
```

seems like doesn't provide anything to use `$pnp`.

I ended up with a temporary solution of impoting the lib druring development:

```javascript
import pnp from 'sp-pnp-js';
declare let $pnp = pnp;
```

and switching to declaring $pnp variable with any data type and without importing the lib before packing before delivering to the site there `$pnp` is deployed globally.

```javascript
declare let $pnp: any;
```

I wondering, can it be done in more elegant way with referencing (`/// <reference path="./../node_modules/sp-pnp-js/dist/pnp.d.ts" />`) only approach?

Thanks!

**Comment by patrick-rodgers** [comment] 2017-03-03 17:00
This is really a duplicate of #330 and isn't a use case I thought would be very high. I anticipated most folks would want to use the library as an import and then mark it external for builds. But now it has come up twice in a week. There was a limitation in TS that was blocking this but I can't remember what that was now. I will have to go back and find that and see where things stand. Going to close this one as a duplicate - but you can follow #330 for updates.

**Closed by patrick-rodgers** 2017-03-03 17:00 UTC
Labels: duplicate

**Comment by koltyakov** [comment] 2017-03-03 21:41
Thanks, Patrick!
Sorry for a duplicate, I really missed this one during a quick search.

**Comment by patrick-rodgers** [comment] 2017-03-03 21:42
No worries at all. But since two people brought it up figured worth investigating. If you get a chance try the proposed solution in the other thread #330.
