### ISSUE TITLE
Error creating build npm PnP JS Core v2 / react js

### ISSUE THREAD

**Issue by AdrianChrobok** [SharePoint/PnP-JS-Core#307] opened 2017-01-26 10:38 UTC
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Observed Behavior
Error by creating a build with npm using react js and referencing to use pnp core js 2:

I created a new empty react project, added and referenced the current PnP JS Core v2 version and always getting an error by running "npm run build". With PnP JS Core 1.x.x I had no issues doing the 

```
> test@0.1.0 build C:\Users\adrian.chrobok\test
> react-scripts build

Creating an optimized production build...
Failed to compile.

static/js/main.ae41314c.js from UglifyJs
SyntaxError: Unexpected token: name (Util) [./~/sp-pnp-js/lib/utils/util.js:2,0]


npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! test@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adrian.chrobok\test\npm-debug.log
```

#### Steps to Reproduce
1. Create a new blank react app (create-react-app NAME)
2. Add the pnp package to the project (npm install sp-pnp-js --save-dev)
3. Import pnp (import pnp from 'sp-pnp-js') inside of the App.js
4. Create an production build (npm run build)

**Comment by patrick-rodgers** [comment] 2017-01-26 14:13
What version of nodejs are you running? With 2.0 the lib folder now contains es6 modules instead of es5 so this might be the issue. You can also review [this guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Moving-from-1.0.*-to-2.0.0) for moving between versions.

**Comment by AdrianChrobok** [comment] 2017-01-26 15:45
@patrick-rodgers Thanks for your answer! Its node v6.9.1

**Comment by mauricionr** [comment] 2017-01-26 15:51
Same issue here, node 7.0.0

**Comment by cOwOsen** [comment] 2017-01-26 16:20
same issue. Without UglifyJs app.js has 

/* WEBPACK VAR INJECTION */(function(global) {
class Util { 
...

not compatible with IE.

**Comment by patrick-rodgers** [comment] 2017-01-26 21:26
Is this [Uglify not handling es6](https://github.com/mishoo/UglifyJS2/issues/448)? I guess I can't see why the library would be causing the issue here. I can load it in a browser and build other things with it. I haven't yet had time to follow your steps. The more details you can provide the easier it is to try and figure out what is not working. Though it might not be something we can necessarily fix on our end.

Perhaps as a work around you can set it as an external somehow and reference it, for example from [the cdn](https://cdnjs.com/libraries/sp-pnp-js).

@cOwOsen - that isn't much information to go on. IE version? What exactly is the issue with that line?

**Comment by cOwOsen** [comment] 2017-01-27 06:51
IE version is 11. Look here [IE11 gives SCRIPT1002 error when defining class in javascript](http://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript).

**Comment by AdrianChrobok** [comment] 2017-01-27 09:49
@patrick-rodgers What kind of details I can provide you in addition to make things easier? Would it help you to add the failed js build? As this issue already happens when you add a reference to the library in a newly created react app, there is nothing I guess nothing I did in addition that could cause this.

**Comment by patrick-rodgers** [comment] 2017-01-27 13:48
@AdrianChrobok if you take Uglify out of the pipeline does it then again work? My question is that is this really a limitation with uglify not supporting es6, as noted in the thread I linked? IF so there no actions for us to take. One solution would be to insert something like babel into your pipeline to ensure what uglify is getting is es5, which it can handle.

**Comment by patrick-rodgers** [comment] 2017-01-27 13:51
@cOwOsen - correct IE11 does not support es6, unsure where you are running into this issue? If it is in the browser, are you using the files from dist? They should be compatible with es5 due to use of babel. If you are building the library using your own toolchain into a single app.js file you would need to handle that in your project.

**Comment by AdrianChrobok** [comment] 2017-01-30 10:45
@patrick-rodgers sorry for the late response! As far as I understand, using the `create-react-app` creates a pre-configured package which uses webpack (incl. UglifyJS) and Babel. It confuses me a little, because I used es6 for my last developments and had no issues with this set up and PnP JS core 1.x.x. Did you already had time to try to reproduce the issue (creating a blank react app, referring to the PnP JS Core)?

**Comment by AdrianChrobok** [comment] 2017-01-30 11:05
I checked the topic a bit further, seems you're right @patrick-rodgers, Uglify is not a friend of es6 ... Found also this article, pretty interesting: https://swizec.com/blog/fun-surprise-uglifyjs-cant-es6/swizec/7272

**Comment by patrick-rodgers** [comment] 2017-01-30 16:40
@AdrianChrobok - going to close this as not a bug. This is a limitation with how they have setup that project. You can report a bug there, or it looks like you can use their "eject" command to edit the config files and update the webpack config to use babel or register this library as an external. I wasn't able to find a way to modify that configuration with what they provided without doing the eject. Regardless I don't see this as a bug as we do provide a packaged file that is compatible with es5 in dist folder, they just haven't given you a way to use it.

**Closed by patrick-rodgers** 2017-01-30 16:40 UTC
Labels: Need More Information
