### ISSUE TITLE
How to save a file property on a list attachment

### ISSUE THREAD

**Issue by sumentse** [SharePoint/PnP-JS-Core#669] opened 2017-12-20 15:41 UTC
#### Category
[ ] Enhancement

[X] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [3.0.2]

#### Expected / Desired Behavior / Question
Dear Community,
I have an issue with attaching a file read through node native fs and attaching it to a SharePoint list. Does anyone know what is the correct way to attach a file from a file stored locally on your computer and attach it to a SharePoint item list? eventually, I would like to make an external application that connects to the SharePoint API using ExpressJS and multer for file attachment for development purposes. 

Below is an example of what I'm trying to do. I expected it to add a file to a SharePoint list item. 

~~~~js
import * as pnp from 'sp-pnp-js';
import NodeFetchClient from 'node-pnp-js';
import fs from 'fs';
import bufferToArrayBuffer  from 'buffer-to-arraybuffer';


pnp.setup({
    sp: {
        fetchClientFactory: () => {
            return new NodeFetchClient({
                username: "test",
                password: "password"
            });
        }
    }
});


let host = new pnp.Web('https://example.com/sites')
let file = bufferToArrayBuffer(fs.readFileSync('/Users/Home/Downloads/Presentation.pdf'));

//this does not work
host.lists.getByTitle("Template%20Upload")
    .items
    .getById(1)
    .attachmentFiles
    .add("Presentation.pdf", file )
    .then((v) => {
        console.log(v);
    }, (err)=>{
        console.log(err.data.responseBody)
    });
~~~~

**Comment by koltyakov** [comment] 2017-12-20 16:33
Any exceptions when running this? Looks correct.
But I have some concerns about username/password only for `node-pnp-js`. `node-sp-auth` expects `domain` as well. You can also try `sp-pnp-node` and ambient initiation to check auth. It'll prompt for credentials:

```typescript
import { Web } from 'sp-pnp-js';
import { PnpNode } from 'sp-pnp-node';

(new PnpNode()).initAmbient().then(async (settings) => {

    let web = new Web(settings.siteUrl);
    /// ... // <<< Here goes PnP JS Core code
    let { Title } = await web.select('Title').get();

   console.log(Title);

}).catch(console.log);
``` 

Web title should be in a console.
Then check `./config/private.json`. And use credentials parameters for `node-pnp-js` or `sp-pnp-node` (they pretty similar).
If it works, attachments should also work.

**Comment by sumentse** [comment] 2017-12-20 19:27
doesn't work for me. I am seeing the Title through. I'm getting this error.  
~~~~
{ error: 
   { code: '-1, System.NotSupportedException',
     message: { lang: 'en-US', value: 'Specified method is not supported.' } } }
~~~~

**Comment by koltyakov** [comment] 2017-12-20 20:20
@sumentse Hm... interesting.
It fails for me too to [add an attachment from Node.js](https://github.com/koltyakov/PnP-JS-Core-Debug/blob/master/runners/addItemAttachment.ts). With the same error as you provided.
At the same time, [almost identical code](https://github.com/koltyakov/sp-rest-proxy/blob/master/test/manual/static/documents.html#L56) works in a browser.
It's pretty late now, I'll check what might be wrong tomorrow or soo.

**Comment by sumentse** [comment] 2017-12-20 20:36
@koltyakov thanks for testing too. I can give you my insights from what I notice.

- The add attachment works if it was a string for a list attachment
- This works the same for a file folder
- I tested if writing an array buffer works in the file folder and get the same error

**Comment by koltyakov** [comment] 2017-12-20 20:39
I just continued with it and also found out that the issue is connected with how we read file content.

```typescript
let content = fs.readFileSync(filePath).toString(); // Will work
// let content = fs.readFileSync(filePath).buffer;   // Won't work
```

Experimenting with `fs.readFile` and formats...

**Comment by patrick-rodgers** [comment] 2018-01-02 14:26
Just reviewing things now that I am back in the office - looks from the thread above that this is not a bug with the library but rather how things are read in node? If so we can close it and possibly add a wiki article to provide the proper guidance.

**Comment by patrick-rodgers** [comment] 2018-01-15 15:03
Closing this as answered. Please _reopen_ if that is not the case. Thanks!

**Closed by patrick-rodgers** 2018-01-15 15:03 UTC
Labels: question
