### ISSUE TITLE
Caching and getItemsByCAMLQuery

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#344] opened 2017-03-03 21:28 UTC
#### Category
[x ] Enhancement

[ ] Bug

[x ] Question

#### Expected / Desired Behavior / Question
I'd expect either the caching to work properly or to have the fact that this method is not supported for caching documented [here](https://github.com/SharePoint/PnP-JS-Core/wiki/Caching) and have the method throw an exception/log something in the console when used in unsupported scenario.
The view xml can of course be dynamic, then I think we could expect either the developer to have a dynamic key that follows the same sequence or to have a subkey which would be a hash of the view.

#### Observed Behavior
Even though the usingCaching method doesn't throw any exception, data is not being cached and requests are made every time the page is refreshed.

#### Steps to Reproduce
```
 pnp.sp.web.lists.getByTitle("MyList")
                .usingCaching({ storeName: "local", expiration: pnp.util.dateAdd(new Date(), "minute", 1440), key: "somekeynoterelatedtootherissue" })
                .getItemsByCAMLQuery({
                    ViewXml:
                    `<View> 
                    <RowLimit> 
                        3 
                    </RowLimit> 
                    <Query> 
                        <Where> 
                            <Leq> 
                                <FieldRef Name='somefield2' /> 
                                <Value IncludeTimeValue='TRUE' Type='DateTime'><Today /></Value> 
                            </Leq> 
                        </Where> 
                        <OrderBy>
                            <FieldRef Name='somefield' Ascending='False' />
                        </OrderBy>
                    </Query> 
                    <ViewFields> 
                        <FieldRef Name='somefield' /> 
                        <FieldRef Name='somefield2' /> 
                    </ViewFields> 
                </View>` })
```

**Comment by patrick-rodgers** [comment] 2017-03-03 21:36
For this one that is actually by design because the _getItemsByCAMLQuery_ method does a POST behind the scenes. We don't process caching for POST queries. I believe you can accomplish the same thing by rewriting your code as:

```TypeScript
pnp.storage.local.getOrPut("somekeynoterelatedtootherissue", () => {

    pnp.sp.web.lists.getByTitle("MyList")
        .getItemsByCAMLQuery({
            ViewXml:
            `<View> 
                    <RowLimit> 
                        3 
                    </RowLimit> 
                    <Query> 
                        <Where> 
                            <Leq> 
                                <FieldRef Name='somefield2' /> 
                                <Value IncludeTimeValue='TRUE' Type='DateTime'><Today /></Value> 
                            </Leq> 
                        </Where> 
                        <OrderBy>
                            <FieldRef Name='somefield' Ascending='False' />
                        </OrderBy>
                    </Query> 
                    <ViewFields> 
                        <FieldRef Name='somefield' /> 
                        <FieldRef Name='somefield2' /> 
                    </ViewFields> 
                </View>` });

}, pnp.util.dateAdd(new Date(), "minute", 1440));
```

**Comment by baywet** [comment] 2017-03-03 21:42
Thanks for the quick answer. 
Maybe the fact that POST related queries are not being cached and therefore this method is not natively supported should be documented on the Caching page? (web-wise this decision makes sense, only the name of the method and the wording on the doc is confusing currently I believe)
I'll try this solution on Monday and let you know

**Comment by baywet** [comment] 2017-03-06 17:51
Totally works, I think both the explanation of why getItemsByCAMLQuery is not being cached and that solution should be documented in the caching section. Should I close this one or do you want to keep it open to track the documentation update?

**Comment by patrick-rodgers** [comment] 2017-03-10 15:51
Closing this as by design. Thanks for the feedback and interest in sp-pnp-js!

**Closed by patrick-rodgers** 2017-03-10 15:51 UTC
Labels: not a bug
