### ISSUE TITLE
Error When the search returns no results  - Cannot read property 'RelevantResults' of null

### ISSUE THREAD

**Issue by deharf** [SharePoint/PnP-JS-Core#337] opened 2017-02-28 18:49 UTC
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

Hi,
I Am Using a sharepoint 2013  Ver: 15.0.4787.1000,  When the search filter condition returns no results,  the error "Can not read property 'RelevantResults' of null" appears in the class SearchResults  ( 

response.PrimaryQueryResult is Null )

Constructor (rawResponse) {
        Let response = rawResponse.postquery? RawResponse.postquery: rawResponse;
        This.PrimarySearchResults = this.formatSearchResults (**response.PrimaryQueryResult.RelevantResults.Table.Rows**);
        This.RawSearchResults = response;
        This.ElapsedTime = response.ElapsedTime;
        This.RowCount = response.PrimaryQueryResult.RelevantResults.RowCount;
        This.TotalRows = response.PrimaryQueryResult.RelevantResults.TotalRows;
        This.TotalRowsIncludingDuplicates = response.PrimaryQueryResult.RelevantResults.TotalRowsIncludingDuplicates;
    }

you can use this sample 

`  pnp.sp.search({
            Querytext: "Moon",
            SelectProperties: ['path', 'Created', 'Title'],
            TrimDuplicates: false
        }).then(data => {
            console.log(data);
        });
`

Thanks!

**Comment by patrick-rodgers** [comment] 2017-03-01 15:34
Thanks @deharf - having a look at this now.

**Comment by patrick-rodgers** [comment] 2017-03-01 15:49
I can't duplicate this currently (don't have a 2013 box up at the moment) - but I believe you. What is interesting is that in SPO even for empty result sets you get the full object tree back. So anyway, easy enough to add some checks to prevent this erroring out. Can you do a debug and provide the raw json object that is being passed into the contructor there, "rawResponse"? I'd like to see what is actually coming back for 2013. Thanks.

**Comment by deharf** [comment] 2017-03-01 18:53
Hi, patrick

After doing some tests with SPO and other CU versions of sharepoint 2013, the code works correctly, it seems that the problem lies in the CU I'm using (January 2016 CU) ([January 2016 CU](https://support.microsoft.com/en-us/help/3114497/january-12,-2016,-cumulative-update-for-sharepoint-server-2013-kb3114497))


When i will give the correct CU that corrects this error, i will post again here

Anyway i  attach the two JSON of the  Post call and Sharepoint response 

Request: 
 ```
{
 "request": {
    "__metadata": {
      "type": "Microsoft.Office.Server.Search.REST.SearchRequest"
    },
    "Querytext": "Moon",
    "SelectProperties": {
      "results": [
        "path",
        "Created",
        "Title"
      ]
    },
    "TrimDuplicates": false
  }
}
```

## Response: 
 ```
{
  "postquery": {
    "__metadata": {
      "type": "Microsoft.Office.Server.Search.REST.SearchResult"
    },
    "ElapsedTime": 895,
    "PrimaryQueryResult": null,
    "Properties": {
      "results": [
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "RowLimit",
          "Value": "10",
          "ValueType": "Edm.Int32"
        },
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "SourceId",
          "Value": "8413cd39-2156-4e00-b54d-11efd9abdb89",
          "ValueType": "Edm.Guid"
        },
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "WasGroupRestricted",
          "Value": "false",
          "ValueType": "Edm.Boolean"
        },
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "IsPartial",
          "Value": "false",
          "ValueType": "Edm.Boolean"
        },
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "EnableInterleaving",
          "Value": "true",
          "ValueType": "Edm.Boolean"
        },
        {
          "__metadata": {
            "type": "SP.KeyValue"
          },
          "Key": "SerializedQuery",
          "Value": "<Query Culture=\"en-GB\" EnableStemming=\"True\" EnablePhonetic=\"False\" EnableNicknames=\"False\" IgnoreAllNoiseQuery=\"True\" SummaryLength=\"180\" MaxSnippetLength=\"180\" DesiredSnippetLength=\"90\" KeywordInclusion=\"0\" QueryText=\"Moon\" QueryTemplate=\"\" TrimDuplicates=\"False\" Site=\"802d1167-6d0a-4cef-8d16-bad3dcf9f172\" Web=\"60389b74-a0a9-4d38-95a4-5bb4e69f2dc9\" KeywordType=\"True\" HiddenConstraints=\"\" />",
          "ValueType": "Edm.String"
        }
      ]
    },
    "SecondaryQueryResults": {
      "__metadata": {
        "type": "Collection(Microsoft.Office.Server.Search.REST.QueryResult)"
      },
      "results": [
        {
          "CustomResults": {
            "__metadata": {
              "type": "Collection(Microsoft.Office.Server.Search.REST.CustomResult)"
            },
            "results": []
          },
          "QueryId": "BestBet Query",
          "QueryRuleId": "00000000-0000-0000-0000-000000000000",
          "RefinementResults": null,
          "RelevantResults": null,
          "SpecialTermResults": {
            "__metadata": {
              "type": "Microsoft.Office.Server.Search.REST.SpecialTermResults"
            },
            "GroupTemplateId": null,
            "ItemTemplateId": null,
            "Properties": {
              "results": [
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "ExecutionTimeMs",
                  "Value": "16",
                  "ValueType": "Edm.Int32"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "QueryModification",
                  "Value": "Moon",
                  "ValueType": "Edm.String"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsPinnedResultBlock",
                  "Value": "true",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "RenderTemplateId",
                  "Value": "~sitecollection/_catalogs/masterpage/Display Templates/Search/Group_Default.js",
                  "ValueType": "Edm.String"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "StartRecord",
                  "Value": "0",
                  "ValueType": "Edm.Int32"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsLastBlockInSubstrate",
                  "Value": "true",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsFirstBlockInSubstrate",
                  "Value": "false",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsFirstPinnedResultBlock",
                  "Value": "true",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsLastPinnedResultBlock",
                  "Value": "true",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsFirstRankedResultBlock",
                  "Value": "false",
                  "ValueType": "Edm.Boolean"
                },
                {
                  "__metadata": {
                    "type": "SP.KeyValue"
                  },
                  "Key": "IsLastRankedResultBlock",
                  "Value": "false",
                  "ValueType": "Edm.Boolean"
                }
              ]
            },
            "Results": {
              "__metadata": {
                "type": "Collection(Microsoft.Office.Server.Search.REST.SpecialTermResult)"
              },
              "results": [
                {
                  "Description": "",
                  "IsVisualBestBet": false,
                  "PiSearchResultId": null,
                  "RenderTemplateId": "~sitecollection/_catalogs/masterpage/Display Templates/Search/Item_BestBet.js",
                  "Title": "Sharepoint Online",
                  "Url": null
                }
              ]
            },
            "ResultTitle": "",
            "ResultTitleUrl": null
          }
        }
      ]
    },
    "SpellingSuggestion": "",
    "TriggeredRules": {
      "__metadata": {
        "type": "Collection(Edm.Guid)"
      },
      "results": [
        "97fd3bea-4956-4c42-b960-4190b6a82e59"
      ]
    }
  }
}
 ```

**Comment by patrick-rodgers** [comment] 2017-03-01 19:07
Ok, thanks for letting us know. I'll keep this open for now but have removed the bug label as it might be just an issue with a particular CU. If you can recreate let me know otherwise this issue will be closed in a few days. Thanks!

**Comment by patrick-rodgers** [comment] 2017-03-09 13:55
Closing this as not a bug, please reopen if needed. Thanks!

**Closed by patrick-rodgers** 2017-03-09 13:55 UTC
Labels: investigate, Need More Information
