### ISSUE TITLE
ERROR Error: Uncaught (in promise): SyntaxError: Invalid character

### ISSUE THREAD

**Issue by hmendezm** [SharePoint/PnP-JS-Core#597] opened 2017-09-19 20:29 UTC
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

3.0.0 

#### Expected / Desired Behavior / Question
I want to check if the current user has permission to a specific site by using getCurrentUserEffectivePermissions and hasPermissions.

#### Observed Behavior
When I am trying to use getCurrentUserEffectivePermissions() as your example I got the error "ERROR Error: Uncaught (in promise): SyntaxError: Invalid character". I get the same error with pnp.sp.web.roleAssignments but I was able to fix using .configure. However, it is not working with getCurrentUserEffectivePermissions.

#### Steps to Reproduce
I am using Angular 2 and I have the below method in my service. when the code run I get the error "ERROR Error: Uncaught (in promise): SyntaxError: Invalid character"

`pnp.sp.web.configure({
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json;odata=verbose'
            }
        }).getCurrentUserEffectivePermissions().then(perms => {

            console.log(perms);
        });
`
I trying to use pnp.setup() but it is not found. What should I do to get working this?

**Comment by patrick-rodgers** [comment] 2017-09-19 21:01
What does the username look like for the current user? Can you share it (feel free to replace any alpha chars with x's) just trying to figure out what the invalid char might be. I can't reproduce this with what I've got.

**Comment by hmendezm** [comment] 2017-09-20 13:08
Hi Patrick-Rodgers

Thank you very much for your reply. The username looks like i:0#.w|DOMAIN\Username. I am using SharePoint 2013 and the app is developing in Angular 2.

Best Regards
hmendezm

**Comment by patrick-rodgers** [comment] 2017-09-20 15:02
is there a ' char in the username? I can't see where this would be coming from unless there is a weird char embedded in the string. What happens under the hood is we get the current LoginName and then call getUserEffectivePermissions with that login name. Only thing I can think is that there is a "'" in the login name and it is breaking the querystring param in the call to getUserEffectivePermissions because we wrap it in single quotes.

**Comment by hmendezm** [comment] 2017-09-20 16:48
I tested the   getUserEffectivePermissions function that allows me to pass the login with two cases.
1. pass the username with @site.XXX format (This works)
2. pass the username with domain\username format (This does not work). is it possible that "\" is the invalid char? 
CASE 1
pnp.sp.web.getUserEffectivePermissions('i:0#.w|membership|username@site.domain').then(perms => {

                            console.log(perms);
                        });
CASE 2
        pnp.sp.web.getUserEffectivePermissions('i:0#.w|membership|Domain\username').then(perms => {

               console.log(perms);
            });

I hope this info help. is it a way I can pass the username to getCurrentUserEffectivePermissions()? I checked the function and I do not see any parameter and actually I saw that pnp use this to get the username.

Best Regards
hmendezm

**Comment by patrick-rodgers** [comment] 2017-09-20 16:57
You would need to pass whatever comes back as the login name of the user from SharePoint. For example you could use this to get the loginname for the current user:

```
pnp.sp.web.currentUser.select("LoginName").get().then(n => console.log(n));
```

If you are passing the string literal with a "\\" in it then, yes it might need to be escaped with an extra slash - or the system is expecting the first format you listed.

**Comment by hmendezm** [comment] 2017-09-20 19:46
The problem is that I need to use getCurrentUserEffectivePermissions() function and I do not have control of the username format because the sp-pnp-js library gets the username value internally. How can I pass the username to the function ? I need to do what you have in the wiki page but I do not see a way to pass the username so I can add an extra slah.

**Has Permissions**

If you need to check multiple permissions it can be more efficient to get the BasePermissions once and then use the hasPermissions method to check them as shown below. This method was introduced in 2.0.3.

```
pnp.sp.web.getCurrentUserEffectivePermissions().then(perms => {

    if (pnp.sp.web.hasPermissions(perms, PermissionKind.AddListItems) && pnp.sp.web.hasPermissions(perms, PermissionKind.DeleteVersions)) {

        // ...
    }
});
```

**Comment by patrick-rodgers** [comment] 2017-11-27 14:09
Hi @hmendezm - are you still having issues here? I am back from family leave so am catching up. You can get an individual's permissions using the `getUserEffectivePermissions` method that takes a username. This is one I see I wasn't able to reproduce before. Thanks!

**Comment by hmendezm** [comment] 2017-11-29 19:05
I used  getSubWebsFilteredForCurrentUSer. See below
.getSubwebsFilteredForCurrentUser()
      .get()
      .then(function(searchResult) {
        return searchResult.map(function(x) {
          return { title: x.Title, relativeUrl: x.ServerRelativeUrl };
        });
      })


Thanks Patrick

**Comment by patrick-rodgers** [comment] 2017-11-29 20:47
Great! Glad to hear you got things moving. I'll close this issue then. Thanks!

**Closed by patrick-rodgers** 2017-11-29 20:47 UTC
Labels: investigate, Need More Information
