### ISSUE TITLE
How to read the html content of page using GetFileByServerRelativeUrl in REST API

### ISSUE THREAD

**Issue by spvjebaraj** [SharePoint/PnP-JS-Core#581] opened 2017-09-06 12:05 UTC
Hi,
I am working in SharePoint Online project and my requirement should read the html content of page. This page contains the content query web part output. I used the below query but am unable to get the html content.
https://mydomain.sharepoint.com/sites/dev-sp1/_api/web/GetFileByServerRelativeUrl('/sites/dev-sp1/en/app-lib/home-service.aspx')/$value

Let us assume the below contents are displayed in the page.

**Navigation** **Links** - **Content Query Web Part Title**
- Test Menu 1
- Test Menu 2
- Test Menu 3

I want to get these information as html format. Could you please suggest any one how to achieve this?

Thanks,
Philip

**Comment by russgove** [comment] 2017-09-06 12:27
You could probably us jquery to select content out of it.

**Comment by koltyakov** [comment] 2017-09-06 12:29
Hi Philip,

I guess you asked this exact question a couple of times ([#479](https://github.com/SharePoint/PnP-JS-Core/issues/479), [#477](https://github.com/SharePoint/PnP-JS-Core/issues/477)) and got the answer.
Is there any difference in this issue with previously discussed?

You shouldn't use REST API to get resulted page content as an HTML. This can be achieved with an HTTP request to the page using jQuery, Fetch, [HttpClient](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/net/httpclient.ts) within the PnP-JS-Core library, etc.

With `/$value` (`pnp.sp.web.getFileByServerRelativeUrl('/path-to-page/page.aspx').getText().then(console.log)`) you'll receive aspx's content instead.

**Comment by spvjebaraj** [comment] 2017-09-06 12:50
Hi Andrew,
Thanks for your replies. Yes, I asked the same question, but it takes 3 to 5 seconds to get the content in Chrome and in IE it takes 5 to 7 seconds. Is they any alternate solution to reduce the time?

Thanks in advance.

**Comment by koltyakov** [comment] 2017-09-06 13:10
In the end of the day, you need to extract some data from a CQWP or, actually, to get the same data which is rolling up to the webpart, aren't you?
I would recommend concentrating attention on the initial data source. It can be so, that reproducing the same logical data request is not a big deal. For instance, the source data might have been received using search request in milliseconds.
Alternatively, some schedule-base data preparation or client side caching can be used.
But, so far, it's just a blind guessing as we know nothing about your actual task or goal. =)

**Comment by spvjebaraj** [comment] 2017-09-06 13:28
Thanks for sharing the details.. My goal is below.
I want to display the content to the user based on target audience applied in list or pages (such as news articles). There is no API in Client Object Model to filter out the results based on target audience. In server side code, we can achieve this easily.

For this scenario, we created dummy "aspx" web part page and add the CQWP with the respective settings to display the content. From this page, we have to get the content and displayed in home page.

**Comment by koltyakov** [comment] 2017-09-06 13:56
Oh, this makes much more sense. Kind of a hairy task. Suggested methods above definitely won't work. 
What if to place your CQWP right on the welcome page, decorate it a bit or hide if needed?
Maybe somebody else will suggest a better solution. I always ended up not using target audience.

**Comment by spvjebaraj** [comment] 2017-09-06 14:13
Thanks for sharing the details Andrew. If anybody knows better solution kindly let me know.

**Comment by patrick-rodgers** [comment] 2017-09-11 15:48
What about an iframe of that page? Or possibly using search? Or just placing the audience targeted web part on the page? This seems over engineered - so maybe revisit the actual problem you want to solve and look for alternatives.

This seems to be more of a general design question and not specific to the library I'd encourage you to post it in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) and folks might have ideas on helping with the design.

Going to close this issue for now, but if you need help with this task specific to the library please do _reopen_ so folks can assist. Thanks!

**Closed by patrick-rodgers** 2017-09-11 15:48 UTC
