### ISSUE TITLE
The use of ensure method requires elevated permissions even if object already exists

### ISSUE THREAD

**Issue by kayodebristol** [SharePoint/PnP-JS-Core#540] opened 2017-07-26 12:38 UTC
#### Category
[X] Enhancement

[X] Bug

[ ] Question

#### Version
v2.0.6 

Will check the latest version. 

#### Expected / Desired Behavior / Question
The use of ensure method should check for existence first (only read permissions should be required). Create object if and only if existence returns false. 

#### Observed Behavior
Ensure returns a promise and a result. Even if the object already exists (result.created == false), ensure requires the executor of the script to have rights to create to the object. 

#### Steps to Reproduce
1. Create a list called ensureTest. 
2. Create a script that uses ensure to create that list if it doesn't already exist. 
pnp.sp.web.lists.ensure('ensureTest').then(function(result){
     if(result.created){console.log("Ensure created this list for you");}
     else{console.log("This list already exists");}
});
3. Place the script in a CEWP. 
4. Logon with a user that only has read permissions
5. Notice that even though the list was created in step one, you are prompted for permissions.

This functionality prevents ensure from being truly useful. I.e., create the list the moment I place the script in the CEWP with my design permissions or higher, but do nothing when an end user navigates to the page with read or perhaps lower permissions. Since the list would always get created on first execution and first execution would ~always be by a person with appropriate permissions, ensure would be super useful.

**Comment by patrick-rodgers** [comment] 2017-07-27 03:33
Ok, thanks, will have a look.

**Comment by patrick-rodgers** [comment] 2017-08-01 20:32
Thinking about this - I am not sure use of the ensure method is correct in situations where the user may not have rights to create/update the list. The issue is that we do an update based on the supplied settings if the list exists, hence the need for "elevated" permissions. So we would have to update the method behavior.

What behavior would you expect if the user doesn't have the correct rights and the list doesn't exist? The list wouldn't be there and I assume (always dangerous) that the rest of your logic behind that ensure call would fail.

 I think the recommendation is to not use ensure and just use the direct get by title or id. ensure is designed more for provisioning scenarios or where the users will have the necessary rights.

Thoughts?

**Comment by kayodebristol** [comment] 2017-08-02 03:23
2 Points. 
First - If object already exists, ensure requires create permissions. But it isn't creating anything. I see that as problematic in and of itself. To make matters worse, ensure only does meaningful work (creates the object) once, all other times it just does a check, so for the majority of it's executions, ensure requires more permissions than it needs to do meaningful work.  

Second - I write code for designers (folks with rights). Designers deploy my code for their users (folks with limited rights). Ideally, ensure would provision on first execute (by the designer) and do nothing on subsequent executions by the user. Let's say the list gets deleted. Then, on first execution by a designer list would be created again, everyone's Happy. 

Designers have rights to create lists. Users generally have rights to update lists, but not create them. Even if the user only has read rights, that's not ensure's business, especially if the object it's ensuring already exists. 

Users do not have rights to deploy JavaScript. Hence, Designers would also be running the code on first execution. Subsequent execution is where ensure currently fails me. 

The utility of ensure (in theory at least) is that I can write one script and have it work in both situations. Provisioning and end user usage. I fail to see the value of ensure if it causes problems when executed by end users.

**Comment by patrick-rodgers** [comment] 2017-08-03 13:54
What you are missing is that we do an update to the list settings inside ensure. We are ensuring it has the setting you want in the list either in creation or update. That is why those permissions are required. So it does "meaningful" work in updating the list.

I get what you are saying but that is not how this method behaves. Also, I think having a known error condition in your code "no non-designer will ever run my code before a designer" is asking for trouble and isn't the best pattern.

You are missing the goal of ensure: "Ensure this list exists, and has these settings". Given this, other than changing the ensure method's behavior what fix would you propose? We could add a flag to skip the update - would that meet your needs?

**Comment by kayodebristol** [comment] 2017-08-03 15:23
Awesome. Maybe I'm using ensure all wrong. I don't execute code further on until ensure returns with a result. 
In the case of an end user, ensure doesn't return; user is prompted for permission 3 times, then access denied exception, execution ends if it isn't caught. 
Prompting a user to enter credentials if the list does not exist is a good thing or if updates need to be made. However, prompting for credentials when the list already exists and requires no changes is what bothers me about the current behavior of ensure. 

$pnp.sp.web.lists.ensure("NewList").then(function(result){ //Create NewList if it doesn't exist
        if(result.created){ //Create required fields
                $pnp.sp.web.lists.getByTitle("NewList").fields.addText("FieldTxt",255).then(function(){
                        $pnp.sp.web.lists.getByTitle("NewList").fields.addNumber("FieldNum").then(function(){
                                console.log("List and Fields Created");
                                }).then(FurtherOnCode());
                        });
        }
        else{
                console.log("List already Exists");
                FurtherOnCode();
        }

});

**Comment by patrick-rodgers** [comment] 2017-08-14 16:13
I'd recommend updating your code to have a provisioning piece and a regular piece. That way you have two code paths, one to ensure the list is present and the other for users who just need to access the list. As for the login prompts that is also outside the control of the library.

I get what you are trying to do - but when some users have permissions and some don't ensure isn't the best option for universal usage.

I am going to close this issue for now, but please _reopen_ if you would like to continue the conversation.

**Closed by patrick-rodgers** 2017-08-14 16:13 UTC
Labels: Need More Information, not a bug
