### ISSUE TITLE
SharePoint Framework's gulp serve fails after adding sp-pnp-js

### ISSUE THREAD

**Issue by Trickass** [SharePoint/PnP-JS-Core#262] opened 2016-11-16 16:06 UTC
#### Category
[ ] Enhancement

[ X] Bug

[ ] Question

#### Observed Behavior
Running gulp serve on SharePoint Framework project fails after adding and using PNP JS.

#### Steps to Reproduce
Create a new SPFx webpart, install and import `sp-pnp-js`, and run `gulp serve`

```
- yo @microsoft/sharepoint
- npm install sp-pnp-js --save-dev
- import pnp from "sp-pnp-js"
- gulp serve
```

#### Gulp serve output

> C:\Projects\_Demos\OPTMDemo>gulp serve
> Build target: DEBUG
> [16:59:27] Using gulpfile C:\Projects\_Demos\OPTMDemo\gulpfile.js
> [16:59:27] Starting gulp
> [16:59:27] Starting 'serve'...
> [16:59:27] Starting subtask 'pre-copy'...
> [16:59:27] Finished subtask 'pre-copy' after 6.85 ms
> [16:59:27] Starting subtask 'tslint'...
> [16:59:27] Starting subtask 'copyStaticAssets'...
> [16:59:27] Starting subtask 'sass'...
> [16:59:27] Finished subtask 'sass' after 639 ms
> [16:59:27] Starting subtask 'typescript'...
> [16:59:27] [typescript] Using custom version: 2.0.10
> [16:59:27] Finished subtask 'copyStaticAssets' after 689 ms
> [16:59:28] Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-imports: unused import: 'pnp'
> [16:59:28] Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-variable: Unused import: 'pnp'
> [16:59:28] Finished subtask 'tslint' after 1.12 s
> [16:59:32] Error - typescript - node_modules\@types\core-js\index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.
> [16:59:32] Error - typescript - node_modules\@types\core-js\index.d.ts(867,13): error TS2300: Duplicate identifier 'Promise'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(41,14): error TS2300: Duplicate identifier 'RequestInfo'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(42,15): error TS2300: Duplicate identifier 'Request'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(61,11): error TS2300: Duplicate identifier 'Request'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(78,6): error TS2300: Duplicate identifier 'RequestMode'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestCredentials'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestCache'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(84,15): error TS2300: Duplicate identifier 'Response'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
> [16:59:32] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(109,6): error TS2300: Duplicate identifier 'ResponseType'.
> [16:59:32] Error - typescript - typings\es6-promise\es6-promise.d.ts(12,15): error TS2300: Duplicate identifier 'Promise'.
> [16:59:32] Error - typescript - typings\es6-promise\es6-promise.d.ts(43,16): error TS2300: Duplicate identifier 'Promise'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(8,15): error TS2300: Duplicate identifier 'Request'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(22,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of ty
> pe 'HeadersInit', but here has type 'string[] | Headers | { [index: string]: string; }'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(24,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type
> 'RequestMode', but here has type 'string | "same-origin" | "navigate" | "no-cors" | "cors"'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(25,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be o
> f type 'RequestCredentials', but here has type 'string | "same-origin" | "omit" | "include"'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(26,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type
>  'RequestCache', but here has type 'string | "default" | "no-store" | "reload" | "no-cache" | "force-cache" | "only-if-cached"'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(36,14): error TS2300: Duplicate identifier 'RequestMode'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(37,14): error TS2300: Duplicate identifier 'RequestCredentials'.
> [16:59:32] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(38,14): error TS2300: Duplicate identifier 'RequestCache'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(40,15): error TS2300: Duplicate identifier 'Headers'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(58,15): error TS2300: Duplicate identifier 'Response'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(71,14): error TS2300: Duplicate identifier 'ResponseType'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(74,2): error TS2687: All declarations of 'status' must have identical modifiers.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(76,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of ty
> pe 'HeadersInit', but here has type 'HeaderInit'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(80,14): error TS2300: Duplicate identifier 'BodyInit'.
> [16:57:36] Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(81,14): error TS2300: Duplicate identifier 'RequestInfo'.
> [16:57:37] Error - 'typescript' sub task errored after 4.3 s
>  "TypeScript error(s) occurred."
> [16:57:37] 'serve' errored after 5.57 s
> [16:57:37]
> [16:57:37] ==================[ Finished ]==================
> Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-imports: unused import: 'pnp'
> Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-variable: Unused import: 'pnp'
> Error - typescript - node_modules\@types\core-js\index.d.ts(781,11): error TS2300: Duplicate identifier 'Promise'.
> Error - typescript - node_modules\@types\core-js\index.d.ts(867,13): error TS2300: Duplicate identifier 'Promise'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(41,14): error TS2300: Duplicate identifier 'RequestInfo'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(42,15): error TS2300: Duplicate identifier 'Request'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(61,11): error TS2300: Duplicate identifier 'Request'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(78,6): error TS2300: Duplicate identifier 'RequestMode'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestCredentials'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestCache'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(84,15): error TS2300: Duplicate identifier 'Response'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
> Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(109,6): error TS2300: Duplicate identifier 'ResponseType'.
> Error - typescript - typings\es6-promise\es6-promise.d.ts(12,15): error TS2300: Duplicate identifier 'Promise'.
> Error - typescript - typings\es6-promise\es6-promise.d.ts(43,16): error TS2300: Duplicate identifier 'Promise'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(8,15): error TS2300: Duplicate identifier 'Request'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(22,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'Headers
> Init', but here has type 'string[] | Headers | { [index: string]: string; }'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(24,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'RequestMod
> e', but here has type 'string | "same-origin" | "navigate" | "no-cors" | "cors"'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(25,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'Req
> uestCredentials', but here has type 'string | "same-origin" | "omit" | "include"'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(26,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'RequestCa
> che', but here has type 'string | "default" | "no-store" | "reload" | "no-cache" | "force-cache" | "only-if-cached"'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(36,14): error TS2300: Duplicate identifier 'RequestMode'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(37,14): error TS2300: Duplicate identifier 'RequestCredentials'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(38,14): error TS2300: Duplicate identifier 'RequestCache'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(40,15): error TS2300: Duplicate identifier 'Headers'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(58,15): error TS2300: Duplicate identifier 'Response'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(71,14): error TS2300: Duplicate identifier 'ResponseType'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(74,2): error TS2687: All declarations of 'status' must have identical modifiers.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(76,2): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'Headers
> Init', but here has type 'HeaderInit'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(80,14): error TS2300: Duplicate identifier 'BodyInit'.
> Error - typescript - typings\whatwg-fetch\whatwg-fetch.d.ts(81,14): error TS2300: Duplicate identifier 'RequestInfo'.
> Error - 'typescript' sub task errored after 4.3 s
>  "TypeScript error(s) occurred."
> [16:57:38] Project optm-demo version: 0.0.1
> [16:57:38] Build tools version: 0.11.1
> [16:57:38] Node version: v6.9.1
> [16:57:38] Total duration: 9.32 s
> [16:57:38] Task warnings: 2
> Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-imports: unused import: 'pnp'
> Warning - tslint - src\webparts\helloWorld\components\HelloWorld.tsx(7,8): error no-unused-variable: Unused import: 'pnp'
> [16:57:38] Task errors: 31

**Comment by patrick-rodgers** [comment] 2016-11-16 16:09
This is a duplicate of #221 - the work around is to edit the typings and remove:

```
/// <reference path="whatwg-fetch/whatwg-fetch.d.ts" />
/// <reference path="es6-promise/es6-promise.d.ts" />
```

Obviously this is not ideal, but they are in the process of moving to @types system which will fix this before GA. Thanks!

**Closed by patrick-rodgers** 2016-11-16 16:09 UTC

**Comment by Trickass** [comment] 2016-11-18 07:42
Thank you, this made the project build indeed.

However, I did get an error when trying to add the webpart on a classic SharePoint page, after deploying to the App Catalog.
Don't know if this is related...
