### ISSUE TITLE
Sorting Search results not working

### ISSUE THREAD

**Issue by russgove** [SharePoint/PnP-JS-Core#335] opened 2017-02-27 23:24 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

I am trying to get a sorted list of sitecollections using the following code:
`   let querytext = "contentclass:STS_Site ";
  
    console.log("Using Query " + querytext);
    const q: SearchQuery = {
      Querytext: querytext,
      SelectProperties: ["Title", "Description", "SPSiteUrl", "SPWebUrl"],
      RowLimit: 999,
      TrimDuplicates: false,
      SortList:
      [
        {
          Property: 'Title',
          Direction: SortDirection.Ascending
        }
      ]

    };`

it returns a 400(Bad request).
If I remove the sortlist it works fine.
The request being sent to sharepoint with the sortlist is :
`{"request":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchRequest"},"Querytext":"contentclass:STS_Site ","SelectProperties":{"results":["Title","Description","SPSiteUrl","SPWebUrl"]},"RowLimit":999,"TrimDuplicates":false,"SortList":{"results":[{"Property":"Title","Direction":0}]}}}`

**Comment by russgove** [comment] 2017-02-27 23:25
I am using version 2.0.1

**Comment by patrick-rodgers** [comment] 2017-03-01 14:41
Thanks @russgove - taking a look at this one now.

**Comment by patrick-rodgers** [comment] 2017-03-01 15:32
On this one the library seems to work, for example if I change Title to Created it sorts the returned sites by Created date. If I check the search schema I see Created is marked as Sort and Title is not. So it doesn't look like by default you can sort on the titles. You can have a look at [this thread](https://social.technet.microsoft.com/Forums/scriptcenter/en-US/a79d64c2-5dee-4e7f-9293-6aaca173c454/sorting-rest-search-query-by-site-title?forum=sharepointsearch) as a reference.

Going to close this one as the library is working (sending the correctly formatted request) - the error returned is just unfortunately vague but appears to mean that the property is not sortable. Please re-open the issue if you think the problem is with the library.

**Closed by patrick-rodgers** 2017-03-01 15:32 UTC
Labels: in progress!, investigate
