### ISSUE TITLE
Possible to use pnp-js-core in completely external node app with azure ad bearer access token?

### ISSUE THREAD

**Issue by nigel-dewar** [SharePoint/PnP-JS-Core#717] opened 2018-02-06 04:08 UTC
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Using node.js application using express. NOT using TypeScrupt. 
Node App is hosted completely externally. It is NOT an addin.
Node Application authentications  through Azure Dd, hence has an access_token available to use.

#### Expected / Desired Behavior / Question
I would like to pass an access token into the Authorization Headers and be able to use pnp-js against 
my sharepoint online site.

I have tried setting the headers on the pnp setup object, like so

```
const pnp = require('sp-pnp-js')

pnp.setup({
                 sp: {
                     baseUrl: "https://mytenant.sharepoint.com",
                    headers: {
                         "Accept": "application/json;odata=verbose",
                         "Authorization": "Bearer " + token
                     }
                }
 }); 

pnp.sp.web.get().then(r => {
    console.log(r);
}); 
```

But I keep getting an error saying the headers are not set.

(node:20232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: Headers is not defined
(node:20232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is it possible to do what I am doing?

**Comment by koltyakov** [comment] 2018-02-06 06:37
Having a token already, I would suggest @eirikb's [approach](https://gist.github.com/eirikb/5bd691d1471b45d195f3b6ee49d29eb9) which he shared recently in Gitter.

@eirikb, @s-KaiNet, guys, could you please recall what was the issue with using:

```typescript
pnp.setup({
  sp: {
    fetchClientFactory() {
      return new AdalFetchClient("{tenant}", "{app id}", "{app secret}", "sharepoint resource url");
    },
    baseUrl: url
  }
}, url);
```

passing `ssl` keys?

**Comment by eirikb** [comment] 2018-02-06 07:13
Hi

When I stated using adal with SharePoint I had to use a key (SSL key), not a secret. I'm not sure if that is still the case.  
This is how I use the token: https://gist.github.com/eirikb/5bd691d1471b45d195f3b6ee49d29eb9 .
And here is a simplification of how I get the token: https://gist.github.com/eirikb/50132c6bf59dbfb7e174985393a75766

**Comment by nigel-dewar** [comment] 2018-02-06 08:05
Ok sorry doesnt work for me.

Here is what I have tried now

```
const pnp = require('sp-pnp-js')
const fetch = require('node-fetch')

azureAuth(req,res) {
        global.Headers = fetch.Headers;
        global.Request = fetch.Request;
        global.Response = fetch.Response;

      // this is now where I get my azure ad token // bla bla bla
     // I make the post and get my token
request.post(opts, function (err, response, token) {

            if (err) console.log(err)
            //var parsedToken = JSON.parse(token.body);
            var parsedToken = JSON.parse(token);
            var accessToken = parsedToken["access_token"];
            
       // i set the url and baseurl. not sure why 2 different urls are required
      const url = "https://mytenant.sharepoint.com"
        const baseUrl = "https://mytenant.sharepoint.com"

        pnp.setup({
            sp: {
              fetchClientFactory: () => {
                return {
                  fetch: (url, options) => {
                    options.headers.set('Authorization', `Bearer ${accessToken}`);
                    return fetch(url, options);
                  }
                };
              },
              baseUrl
            }
          });

     // now I try to call my web 
        pnp.sp.web.get().then(r => {  
            console.log(r);
        });

} 
```
It doesnt work so I assume something more is needed.

**Comment by eirikb** [comment] 2018-02-06 08:14
Do you get any errors?
It might be you need to define ` global.Headers = fetch.Headers;` early on.  
Also, there is a gitter channel which might be helpful, https://gitter.im/OfficeDev/PnP-JS-Core

**Comment by nigel-dewar** [comment] 2018-02-06 08:20
yes do get errors

(node:15624) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ProcessHttpClientResponseException: Error making HttpClient request in queryable: [401] Unauthorized
(node:15624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks Ill check out the gitter page!

**Comment by nigel-dewar** [comment] 2018-02-06 09:22
@eirikb @koltyakov 

Arrrrggghh! I had just shut down PC for the night as decided to give up and have a crack another day and then I realized after looking at some of the code your provided. 

The token needed to be for the resource, namely SharePoint.  guess which bloody resource I was getting
```
 var url = "https://login.microsoftonline.com/common/oauth2/token";
        var clientSecret = 'mysecret';
        **var resource = 'https://graph.microsoft.com/';**
        var apiUrl = "https://graph.microsoft.com/beta/me";

        var data = 'client_id=myclientid'
            + '&redirect_uri=http://localhost:4200/login'
            + '&client_secret=' + encodeURIComponent(clientSecret)
            + '&grant_type=authorization_code'
            + '&code=' + code
            + '&resource=' + encodeURIComponent(resource);
```

**Comment by koltyakov** [comment] 2018-02-06 09:26
Sound promising! Please let us know if it works for you after binding it all together with a correct resource URL. I believe it should!

**Comment by nigel-dewar** [comment] 2018-02-06 09:27
thank you I will.

**Comment by nigel-dewar** [comment] 2018-02-06 09:42
@koltyakov @eirikb 

Awesome, got it working!!!

IT was essential as you stated to use fetch. Without it wont work.

for others reference, this actually works.

```
const pnp = require('sp-pnp-js')
const fetch = require('node-fetch')

constructor(){
        global.Headers = fetch.Headers;
        global.Request = fetch.Request;
        global.Response = fetch.Response;
}

// GET YOURSELF YOUR ADAL TOKEN. You must target your sharepoint tenant, DONT use graph or  anything like that.
// I used authorization code flow. You do not have to get a token through ssl cert. a standard token will work.

        const url = "https://yourtenant.sharepoint.com"
        const baseUrl = "https://yourtenant.sharepoint.com"

        pnp.setup({
            sp: {
              fetchClientFactory: () => {
                return {
                  fetch: (url, options) => {
                    options.headers.set('Authorization', `Bearer ${accessToken}`);
                    return fetch(url, options);
                  }
                };
              },
              baseUrl
            }
          });
        

           pnp.sp.web.get().then(r => {
            
            console.log(r);
        });
```

**Comment by koltyakov** [comment] 2018-02-06 09:47
Thank you, guys!
Cool, I'm going to close the issue as answered.

**Closed by koltyakov** 2018-02-06 09:47 UTC
Labels: Fixed / Answered

**Comment by patrick-rodgers** [comment] 2018-02-06 13:21
Great stuff. Wanted also to mention we have an [adal fetch client](https://pnp.github.io/pnp/nodejs/adal-fetch-client.html) for node in the new libraries. Should also help here. It will not be transfered back to sp-pnp-js as it doesn't git this library's model.

**Comment by eirikb** [comment] 2018-02-06 13:25
Hi @patrick-rodgers, I might be mistaken, but I think the adal fetch client at the moment only works for Graph, and not SharePoint, because of the resource link, ref https://github.com/pnp/pnp/blob/master/packages/nodejs/src/net/adalfetchclient.ts#L30

**Comment by koltyakov** [comment] 2018-02-06 13:33
@eirikb,

In the first answer example, there is a sample of PnPJS's Adal Fetch client.
And 4th optional parameter stays to the resource. Which can be redefined for SharePoint. 
We discussed this in Gitter, then your ssl situation was revealed. Certificates keys options are not there, that's true.

**Comment by patrick-rodgers** [comment] 2018-02-06 14:10
Yes, and sorry, missed that it was already mentioned at the top of the thread. As usual @koltyakov is way ahead of me :)

**Comment by nigel-dewar** [comment] 2018-02-06 20:12
I did not know about the adal fetch client, so thanks for that, as stated it likely only works with the graph right.

What then would be the difference between pnp graph client vs the official microsoft graph sdk
![image](https://user-images.githubusercontent.com/9402456/35881828-d4649726-0bcd-11e8-9f92-a5f5a73becff.png)


?

**Comment by patrick-rodgers** [comment] 2018-02-06 20:17
@nigel-dewar - there is a 4th parameter that you can change to use the client with SharePoint. No samples for that yet.

When we started our work on the graph client the official sdk didn't exist yet. That library is developed and supported by the graph product team and is similar to the work we did. Big difference is that you need to know the full url and object format to make calls, it doesn't assist you in building the url or creating the objects - though it does have some methods to help with adding odata parameters in a fluent like style.

**Comment by nigel-dewar** [comment] 2018-02-06 20:45
@patrick-rodgers - thanks for answering this.  Im looking at https://github.com/pnp/pnp. Is this a newer version of PnP-JS-Core?

I mean, like a next iteration or evolution. Im just confused because now I see 2 libraries that seem to do the same thing.

Cheers

Nigel

**Comment by patrick-rodgers** [comment] 2018-02-06 20:49
Yes that is the next version of sp-pnp-js - it is live and ready for use. It has a more modular design as well as some improvements not found in sp-pnp-js. Check it out and let us know what you think!

**Comment by nigel-dewar** [comment] 2018-02-06 20:52
Ok thank you very much Patrick. I never would have known about it unless you mentioned it.

heads up to @eirikb 
I did find the section about getting started with SP in node. So this should work.

```
import { sp } from "@pnp/sp";
import { SPFetchClient } from "@pnp/nodejs";

// do this once per page load
sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient("{your site url}", "{your client id}", "{your client secret}");
        },
    },
});

// now make any calls you need using the configured client
sp.web.select("Title").get().then(w => {

    console.log(`Web Title: ${w.Title}`);
});
```

**Comment by patrick-rodgers** [comment] 2018-02-06 20:55
We certainly want to get the word out - so any suggestions on making sure folks are aware is very welcome. We discuss it on the bi-weekly calls and other areas. I guess need to find time to get more communications out.

**Comment by s-KaiNet** [comment] 2018-02-07 07:09
@patrick-rodgers 
>  there is a 4th parameter that you can change to use the client with SharePoint. No samples for that yet.  

You can do that, however to my knowledge, access token generated for SharePoint using client credentials flow with adal library is not valid.   
SharePoint requires tokens with higher level of security, thus forcing us to use certificate-based token generation.  At least it worked that way a year ago.  Checkout great post from @johnnliu [here](http://johnliu.net/blog/2016/5/azure-functions-js-and-app-only-updates-to-sharepoint-online), especially `2.3 Call SharePoint Online` part.

**Comment by patrick-rodgers** [comment] 2018-02-07 14:00
Thanks @s-KaiNet - I'll have to take a look. I thought it you setup an AzureAD app it could work but haven't ever tried it yet. Will give it a shot and see - this may be a place where we can improve the AdalNode client to help.

**Comment by jchilde** [comment] 2018-03-22 23:04
I am not exactly sure where you are using sp-pnp-js; however, if you have a token, you don't need to set global variables or use any particular version of fetch.  I have found that all is required is:

`
                pnp.setup({
                    sp: {
                        headers: {
                            Authorization: 'Bearer ' + res,
                            Accept: "application/json;odata=verbose"
                        }
                    }
                });
               let: web: pnp.Web = new pnp.Web("serverabsoluteurl");
               web.get().then(r => { console.log(r) });
`

**Comment by hamedy** [comment] 2018-05-02 06:52
@jchilde I'm trying to use your approach and can't get it to work. I'm making a web app and the code is all client side. Here's what I have:

const token = "EVkOWJiWGV3PT08L1NQPg=="; //actual token is much longer
const baseUrl = "https://aaaa.sharepoint.com/sites/qhse"
pnp.setup({
  sp: {
    baseUrl: baseUrl,
    headers: {
      Authorization: 'Bearer ' + token,
      Accept: "application/json;odata=verbose"
    }
  }
});

pnp.sp.site.rootWeb.lists.getByTitle("Non Conformities").items.select("Title", "ID", "Status", "ResponsiblePerson/Title", "ProcessName/ID", "DeviationCategory", "Created", "Deadline").expand("ProcessName", "ResponsiblePerson").getAll().then((items: any[]) => {
  items.forEach(element => {
    console.log(element.Title, element.ResponsiblePerson, element.ProcessName)
  });
});

Do you see anything wrong here?

**Comment by jchilde** [comment] 2018-05-02 16:11
@hamedy I am an expert.  I just messed with this until I found something that works for me.  Looking at my code compared to your, I see two obvious differences from the code you are using and the way I have written my code.


1. Try removing the base url from pnp.setup and instead creating a site object directly as:

let site: Site = new Site(baseUrl);   Then do site.rootWeb.lists……

2. See [this](https://github.com/SharePoint/PnP-JS-Core/issues/689).  I suspect that your issue is the same.

**Comment by hamedy** [comment] 2018-05-03 07:12
@jchilde  sorry I didn't mention what the problem is, getting items from the list is ok, I'm getting 403. So If I login to SP and run the code on a SP page without the token stuff, it works fine. When I add the token and run the code on a web app then I get access denied. And inspecting the request, the token is not included in the headers.

**Comment by jchilde** [comment] 2018-05-03 15:09
If what I provided you doesn’t work, I am not sure what you should do.  The code I posted is working fine for me from an Azure hosted web application.

Jeffrey A. Childers
Rumph Childers, LLC
(478) 471-8787 x 7


Confidentiality Notice: This e-mail message and any attachments are for the sole use of the intended recipient(s) and may contain confidential or privileged information.  Any unauthorized review, use, disclosure, or distribution is prohibited.  If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message and any attachments.  The receipt of this email alone does not create an attorney-client privilege.  Thank you.

**Comment by koltyakov** [comment] 2018-05-04 07:55
Hi @hamedy, could you please describe the scenario you're going to achieve?

**Comment by hamedy** [comment] 2018-05-04 08:55
Hi, what we have is a web app hosted in Azure and we want to use pnp in this app to work with SP content. 
We get the token and if I write the following code in the console in my browser it works and returns content from sp:

```
pnp.setup({
  sp: {
    fetchClientFactory: () => {
      return {
        fetch: (url, options) => {
          options.headers.set('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng......');
          return fetch(url, options);
        }
      };
    },
    baseUrl
  }
});
```

But in my development environment, I'm using TypeScript and Webpack etc. Using node-fetch, I get an error in the above code where set function is called on headers. "Property 'set' does not exist on type 'string[][] | { [key: string]: string; }'.
  Property 'set' does not exist on type 'string[][]'."

when I replace that with 
`options.headers = {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng......'}`

or 

`pnp.setup({ sp: { headers: { Authorization: 'Bearer ' + res, Accept: "application/json;odata=verbose" } } }); let: web: pnp.Web = new pnp.Web("serverabsoluteurl"); web.get().then(r => { console.log(r) });`

it no longer works and the headers are not included in the request. So I get access denied. 

Thanks for your time in advance :)

**Comment by DevarshiDave** [comment] 2018-07-03 11:36
@hamedy same issue, have you found any solutions yet?
